# Server settings
server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    root: info

# Spring settings
spring:
  profiles:
    active: dev

# ActiveMQ
activemq:
  broker:
    url: tcp://localhost:61616



