spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2-console
